version: "3.8"

services:
  skud_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_API_BASE_URL: ${PUBLIC_API_BASE_URL}
    container_name: skud_frontend
    ports:
      - "80:80"
    restart: always
