name: skud_face_frontend

version: "3.8"
services:
  skud_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: skud_face_frontend:latest
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "80:80"
    environment:
      SERVER_IP: "${SERVER_IP:-10.1.10.89}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
