name: skud_face_frontend

version: "3.8"
services:
  skud_frontend:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
