/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as AuthRouteImport } from './app/routes/_auth'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthUserAddBatchRouteImport } from './app/routes/_auth/user/add-batch'
import { Route as AuthUserAddRouteImport } from './app/routes/_auth/user/add'

const AuthUserIndexLazyRouteImport = createFileRoute('/_auth/user/')()
const AuthPointIndexLazyRouteImport = createFileRoute('/_auth/point/')()
const AuthOrganizationIndexLazyRouteImport = createFileRoute(
  '/_auth/organization/',
)()
const AuthMonitoringIndexLazyRouteImport =
  createFileRoute('/_auth/monitoring/')()
const AuthDashboardIndexLazyRouteImport = createFileRoute('/_auth/dashboard/')()
const AuthCameraIndexLazyRouteImport = createFileRoute('/_auth/camera/')()
const AuthAdminIndexLazyRouteImport = createFileRoute('/_auth/admin/')()
const AuthPointAddLazyRouteImport = createFileRoute('/_auth/point/add')()
const AuthOrganizationAddLazyRouteImport = createFileRoute(
  '/_auth/organization/add',
)()
const AuthMonitoringHistoryLazyRouteImport = createFileRoute(
  '/_auth/monitoring/history',
)()
const AuthCameraAddLazyRouteImport = createFileRoute('/_auth/camera/add')()
const AuthAdminAddLazyRouteImport = createFileRoute('/_auth/admin/add')()
const AuthUserEditIdLazyRouteImport = createFileRoute('/_auth/user/edit/$id')()
const AuthPointEditIdLazyRouteImport = createFileRoute(
  '/_auth/point/edit/$id',
)()
const AuthOrganizationEditIdLazyRouteImport = createFileRoute(
  '/_auth/organization/edit/$id',
)()
const AuthCameraEditIdLazyRouteImport = createFileRoute(
  '/_auth/camera/edit/$id',
)()
const AuthAdminEditIdLazyRouteImport = createFileRoute(
  '/_auth/admin/edit/$id',
)()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserIndexLazyRoute = AuthUserIndexLazyRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/user/index.lazy').then((d) => d.Route),
)
const AuthPointIndexLazyRoute = AuthPointIndexLazyRouteImport.update({
  id: '/point/',
  path: '/point/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/point/index.lazy').then((d) => d.Route),
)
const AuthOrganizationIndexLazyRoute =
  AuthOrganizationIndexLazyRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./app/routes/_auth/organization/index.lazy').then((d) => d.Route),
  )
const AuthMonitoringIndexLazyRoute = AuthMonitoringIndexLazyRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/monitoring/index.lazy').then((d) => d.Route),
)
const AuthDashboardIndexLazyRoute = AuthDashboardIndexLazyRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/dashboard/index.lazy').then((d) => d.Route),
)
const AuthCameraIndexLazyRoute = AuthCameraIndexLazyRouteImport.update({
  id: '/camera/',
  path: '/camera/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/camera/index.lazy').then((d) => d.Route),
)
const AuthAdminIndexLazyRoute = AuthAdminIndexLazyRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/admin/index.lazy').then((d) => d.Route),
)
const AuthPointAddLazyRoute = AuthPointAddLazyRouteImport.update({
  id: '/point/add',
  path: '/point/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/point/add.lazy').then((d) => d.Route),
)
const AuthOrganizationAddLazyRoute = AuthOrganizationAddLazyRouteImport.update({
  id: '/organization/add',
  path: '/organization/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/organization/add.lazy').then((d) => d.Route),
)
const AuthMonitoringHistoryLazyRoute =
  AuthMonitoringHistoryLazyRouteImport.update({
    id: '/monitoring/history',
    path: '/monitoring/history',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./app/routes/_auth/monitoring/history.lazy').then((d) => d.Route),
  )
const AuthCameraAddLazyRoute = AuthCameraAddLazyRouteImport.update({
  id: '/camera/add',
  path: '/camera/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/camera/add.lazy').then((d) => d.Route),
)
const AuthAdminAddLazyRoute = AuthAdminAddLazyRouteImport.update({
  id: '/admin/add',
  path: '/admin/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/admin/add.lazy').then((d) => d.Route),
)
const AuthUserAddBatchRoute = AuthUserAddBatchRouteImport.update({
  id: '/user/add-batch',
  path: '/user/add-batch',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserAddRoute = AuthUserAddRouteImport.update({
  id: '/user/add',
  path: '/user/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserEditIdLazyRoute = AuthUserEditIdLazyRouteImport.update({
  id: '/user/edit/$id',
  path: '/user/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/user/edit.$id.lazy').then((d) => d.Route),
)
const AuthPointEditIdLazyRoute = AuthPointEditIdLazyRouteImport.update({
  id: '/point/edit/$id',
  path: '/point/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/point/edit.$id.lazy').then((d) => d.Route),
)
const AuthOrganizationEditIdLazyRoute =
  AuthOrganizationEditIdLazyRouteImport.update({
    id: '/organization/edit/$id',
    path: '/organization/edit/$id',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./app/routes/_auth/organization/edit.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCameraEditIdLazyRoute = AuthCameraEditIdLazyRouteImport.update({
  id: '/camera/edit/$id',
  path: '/camera/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/camera/edit.$id.lazy').then((d) => d.Route),
)
const AuthAdminEditIdLazyRoute = AuthAdminEditIdLazyRouteImport.update({
  id: '/admin/edit/$id',
  path: '/admin/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/admin/edit.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/add': typeof AuthUserAddRoute
  '/user/add-batch': typeof AuthUserAddBatchRoute
  '/admin/add': typeof AuthAdminAddLazyRoute
  '/camera/add': typeof AuthCameraAddLazyRoute
  '/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/organization/add': typeof AuthOrganizationAddLazyRoute
  '/point/add': typeof AuthPointAddLazyRoute
  '/admin': typeof AuthAdminIndexLazyRoute
  '/camera': typeof AuthCameraIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/monitoring': typeof AuthMonitoringIndexLazyRoute
  '/organization': typeof AuthOrganizationIndexLazyRoute
  '/point': typeof AuthPointIndexLazyRoute
  '/user': typeof AuthUserIndexLazyRoute
  '/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/add': typeof AuthUserAddRoute
  '/user/add-batch': typeof AuthUserAddBatchRoute
  '/admin/add': typeof AuthAdminAddLazyRoute
  '/camera/add': typeof AuthCameraAddLazyRoute
  '/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/organization/add': typeof AuthOrganizationAddLazyRoute
  '/point/add': typeof AuthPointAddLazyRoute
  '/admin': typeof AuthAdminIndexLazyRoute
  '/camera': typeof AuthCameraIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/monitoring': typeof AuthMonitoringIndexLazyRoute
  '/organization': typeof AuthOrganizationIndexLazyRoute
  '/point': typeof AuthPointIndexLazyRoute
  '/user': typeof AuthUserIndexLazyRoute
  '/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/user/add': typeof AuthUserAddRoute
  '/_auth/user/add-batch': typeof AuthUserAddBatchRoute
  '/_auth/admin/add': typeof AuthAdminAddLazyRoute
  '/_auth/camera/add': typeof AuthCameraAddLazyRoute
  '/_auth/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/_auth/organization/add': typeof AuthOrganizationAddLazyRoute
  '/_auth/point/add': typeof AuthPointAddLazyRoute
  '/_auth/admin/': typeof AuthAdminIndexLazyRoute
  '/_auth/camera/': typeof AuthCameraIndexLazyRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexLazyRoute
  '/_auth/monitoring/': typeof AuthMonitoringIndexLazyRoute
  '/_auth/organization/': typeof AuthOrganizationIndexLazyRoute
  '/_auth/point/': typeof AuthPointIndexLazyRoute
  '/_auth/user/': typeof AuthUserIndexLazyRoute
  '/_auth/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/_auth/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/_auth/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/_auth/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/_auth/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user/add'
    | '/user/add-batch'
    | '/admin/add'
    | '/camera/add'
    | '/monitoring/history'
    | '/organization/add'
    | '/point/add'
    | '/admin'
    | '/camera'
    | '/dashboard'
    | '/monitoring'
    | '/organization'
    | '/point'
    | '/user'
    | '/admin/edit/$id'
    | '/camera/edit/$id'
    | '/organization/edit/$id'
    | '/point/edit/$id'
    | '/user/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user/add'
    | '/user/add-batch'
    | '/admin/add'
    | '/camera/add'
    | '/monitoring/history'
    | '/organization/add'
    | '/point/add'
    | '/admin'
    | '/camera'
    | '/dashboard'
    | '/monitoring'
    | '/organization'
    | '/point'
    | '/user'
    | '/admin/edit/$id'
    | '/camera/edit/$id'
    | '/organization/edit/$id'
    | '/point/edit/$id'
    | '/user/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/user/add'
    | '/_auth/user/add-batch'
    | '/_auth/admin/add'
    | '/_auth/camera/add'
    | '/_auth/monitoring/history'
    | '/_auth/organization/add'
    | '/_auth/point/add'
    | '/_auth/admin/'
    | '/_auth/camera/'
    | '/_auth/dashboard/'
    | '/_auth/monitoring/'
    | '/_auth/organization/'
    | '/_auth/point/'
    | '/_auth/user/'
    | '/_auth/admin/edit/$id'
    | '/_auth/camera/edit/$id'
    | '/_auth/organization/edit/$id'
    | '/_auth/point/edit/$id'
    | '/_auth/user/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/user/': {
      id: '/_auth/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/': {
      id: '/_auth/point/'
      path: '/point'
      fullPath: '/point'
      preLoaderRoute: typeof AuthPointIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/': {
      id: '/_auth/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthOrganizationIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitoring/': {
      id: '/_auth/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthMonitoringIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/': {
      id: '/_auth/camera/'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof AuthCameraIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/add': {
      id: '/_auth/point/add'
      path: '/point/add'
      fullPath: '/point/add'
      preLoaderRoute: typeof AuthPointAddLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/add': {
      id: '/_auth/organization/add'
      path: '/organization/add'
      fullPath: '/organization/add'
      preLoaderRoute: typeof AuthOrganizationAddLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitoring/history': {
      id: '/_auth/monitoring/history'
      path: '/monitoring/history'
      fullPath: '/monitoring/history'
      preLoaderRoute: typeof AuthMonitoringHistoryLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/add': {
      id: '/_auth/camera/add'
      path: '/camera/add'
      fullPath: '/camera/add'
      preLoaderRoute: typeof AuthCameraAddLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/add': {
      id: '/_auth/admin/add'
      path: '/admin/add'
      fullPath: '/admin/add'
      preLoaderRoute: typeof AuthAdminAddLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/add-batch': {
      id: '/_auth/user/add-batch'
      path: '/user/add-batch'
      fullPath: '/user/add-batch'
      preLoaderRoute: typeof AuthUserAddBatchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/add': {
      id: '/_auth/user/add'
      path: '/user/add'
      fullPath: '/user/add'
      preLoaderRoute: typeof AuthUserAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/edit/$id': {
      id: '/_auth/user/edit/$id'
      path: '/user/edit/$id'
      fullPath: '/user/edit/$id'
      preLoaderRoute: typeof AuthUserEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/edit/$id': {
      id: '/_auth/point/edit/$id'
      path: '/point/edit/$id'
      fullPath: '/point/edit/$id'
      preLoaderRoute: typeof AuthPointEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/edit/$id': {
      id: '/_auth/organization/edit/$id'
      path: '/organization/edit/$id'
      fullPath: '/organization/edit/$id'
      preLoaderRoute: typeof AuthOrganizationEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/edit/$id': {
      id: '/_auth/camera/edit/$id'
      path: '/camera/edit/$id'
      fullPath: '/camera/edit/$id'
      preLoaderRoute: typeof AuthCameraEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/edit/$id': {
      id: '/_auth/admin/edit/$id'
      path: '/admin/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthAdminEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthUserAddRoute: typeof AuthUserAddRoute
  AuthUserAddBatchRoute: typeof AuthUserAddBatchRoute
  AuthAdminAddLazyRoute: typeof AuthAdminAddLazyRoute
  AuthCameraAddLazyRoute: typeof AuthCameraAddLazyRoute
  AuthMonitoringHistoryLazyRoute: typeof AuthMonitoringHistoryLazyRoute
  AuthOrganizationAddLazyRoute: typeof AuthOrganizationAddLazyRoute
  AuthPointAddLazyRoute: typeof AuthPointAddLazyRoute
  AuthAdminIndexLazyRoute: typeof AuthAdminIndexLazyRoute
  AuthCameraIndexLazyRoute: typeof AuthCameraIndexLazyRoute
  AuthDashboardIndexLazyRoute: typeof AuthDashboardIndexLazyRoute
  AuthMonitoringIndexLazyRoute: typeof AuthMonitoringIndexLazyRoute
  AuthOrganizationIndexLazyRoute: typeof AuthOrganizationIndexLazyRoute
  AuthPointIndexLazyRoute: typeof AuthPointIndexLazyRoute
  AuthUserIndexLazyRoute: typeof AuthUserIndexLazyRoute
  AuthAdminEditIdLazyRoute: typeof AuthAdminEditIdLazyRoute
  AuthCameraEditIdLazyRoute: typeof AuthCameraEditIdLazyRoute
  AuthOrganizationEditIdLazyRoute: typeof AuthOrganizationEditIdLazyRoute
  AuthPointEditIdLazyRoute: typeof AuthPointEditIdLazyRoute
  AuthUserEditIdLazyRoute: typeof AuthUserEditIdLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUserAddRoute: AuthUserAddRoute,
  AuthUserAddBatchRoute: AuthUserAddBatchRoute,
  AuthAdminAddLazyRoute: AuthAdminAddLazyRoute,
  AuthCameraAddLazyRoute: AuthCameraAddLazyRoute,
  AuthMonitoringHistoryLazyRoute: AuthMonitoringHistoryLazyRoute,
  AuthOrganizationAddLazyRoute: AuthOrganizationAddLazyRoute,
  AuthPointAddLazyRoute: AuthPointAddLazyRoute,
  AuthAdminIndexLazyRoute: AuthAdminIndexLazyRoute,
  AuthCameraIndexLazyRoute: AuthCameraIndexLazyRoute,
  AuthDashboardIndexLazyRoute: AuthDashboardIndexLazyRoute,
  AuthMonitoringIndexLazyRoute: AuthMonitoringIndexLazyRoute,
  AuthOrganizationIndexLazyRoute: AuthOrganizationIndexLazyRoute,
  AuthPointIndexLazyRoute: AuthPointIndexLazyRoute,
  AuthUserIndexLazyRoute: AuthUserIndexLazyRoute,
  AuthAdminEditIdLazyRoute: AuthAdminEditIdLazyRoute,
  AuthCameraEditIdLazyRoute: AuthCameraEditIdLazyRoute,
  AuthOrganizationEditIdLazyRoute: AuthOrganizationEditIdLazyRoute,
  AuthPointEditIdLazyRoute: AuthPointEditIdLazyRoute,
  AuthUserEditIdLazyRoute: AuthUserEditIdLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
