/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as AuthRouteImport } from './app/routes/_auth'
import { Route as R403RouteImport } from './app/routes/403'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthUserIndexRouteImport } from './app/routes/_auth/user/index'
import { Route as AuthPointIndexRouteImport } from './app/routes/_auth/point/index'
import { Route as AuthOrganizationIndexRouteImport } from './app/routes/_auth/organization/index'
import { Route as AuthCameraIndexRouteImport } from './app/routes/_auth/camera/index'
import { Route as AuthAdminIndexRouteImport } from './app/routes/_auth/admin/index'
import { Route as AuthUserAddBatchRouteImport } from './app/routes/_auth/user/add-batch'
import { Route as AuthUserAddRouteImport } from './app/routes/_auth/user/add'
import { Route as AuthPointAddRouteImport } from './app/routes/_auth/point/add'
import { Route as AuthOrganizationAddRouteImport } from './app/routes/_auth/organization/add'
import { Route as AuthCameraAddRouteImport } from './app/routes/_auth/camera/add'
import { Route as AuthAdminAddRouteImport } from './app/routes/_auth/admin/add'

const AuthMonitoringIndexLazyRouteImport =
  createFileRoute('/_auth/monitoring/')()
const AuthDashboardIndexLazyRouteImport = createFileRoute('/_auth/dashboard/')()
const AuthMonitoringHistoryLazyRouteImport = createFileRoute(
  '/_auth/monitoring/history',
)()
const AuthUserEditIdLazyRouteImport = createFileRoute('/_auth/user/edit/$id')()
const AuthPointEditIdLazyRouteImport = createFileRoute(
  '/_auth/point/edit/$id',
)()
const AuthOrganizationEditIdLazyRouteImport = createFileRoute(
  '/_auth/organization/edit/$id',
)()
const AuthCameraEditIdLazyRouteImport = createFileRoute(
  '/_auth/camera/edit/$id',
)()
const AuthAdminEditIdLazyRouteImport = createFileRoute(
  '/_auth/admin/edit/$id',
)()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMonitoringIndexLazyRoute = AuthMonitoringIndexLazyRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/monitoring/index.lazy').then((d) => d.Route),
)
const AuthDashboardIndexLazyRoute = AuthDashboardIndexLazyRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/dashboard/index.lazy').then((d) => d.Route),
)
const AuthUserIndexRoute = AuthUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPointIndexRoute = AuthPointIndexRouteImport.update({
  id: '/point/',
  path: '/point/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationIndexRoute = AuthOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCameraIndexRoute = AuthCameraIndexRouteImport.update({
  id: '/camera/',
  path: '/camera/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonitoringHistoryLazyRoute =
  AuthMonitoringHistoryLazyRouteImport.update({
    id: '/monitoring/history',
    path: '/monitoring/history',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./app/routes/_auth/monitoring/history.lazy').then((d) => d.Route),
  )
const AuthUserAddBatchRoute = AuthUserAddBatchRouteImport.update({
  id: '/user/add-batch',
  path: '/user/add-batch',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserAddRoute = AuthUserAddRouteImport.update({
  id: '/user/add',
  path: '/user/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPointAddRoute = AuthPointAddRouteImport.update({
  id: '/point/add',
  path: '/point/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationAddRoute = AuthOrganizationAddRouteImport.update({
  id: '/organization/add',
  path: '/organization/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCameraAddRoute = AuthCameraAddRouteImport.update({
  id: '/camera/add',
  path: '/camera/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAddRoute = AuthAdminAddRouteImport.update({
  id: '/admin/add',
  path: '/admin/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserEditIdLazyRoute = AuthUserEditIdLazyRouteImport.update({
  id: '/user/edit/$id',
  path: '/user/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/user/edit.$id.lazy').then((d) => d.Route),
)
const AuthPointEditIdLazyRoute = AuthPointEditIdLazyRouteImport.update({
  id: '/point/edit/$id',
  path: '/point/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/point/edit.$id.lazy').then((d) => d.Route),
)
const AuthOrganizationEditIdLazyRoute =
  AuthOrganizationEditIdLazyRouteImport.update({
    id: '/organization/edit/$id',
    path: '/organization/edit/$id',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./app/routes/_auth/organization/edit.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCameraEditIdLazyRoute = AuthCameraEditIdLazyRouteImport.update({
  id: '/camera/edit/$id',
  path: '/camera/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/camera/edit.$id.lazy').then((d) => d.Route),
)
const AuthAdminEditIdLazyRoute = AuthAdminEditIdLazyRouteImport.update({
  id: '/admin/edit/$id',
  path: '/admin/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/admin/edit.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/admin/add': typeof AuthAdminAddRoute
  '/camera/add': typeof AuthCameraAddRoute
  '/organization/add': typeof AuthOrganizationAddRoute
  '/point/add': typeof AuthPointAddRoute
  '/user/add': typeof AuthUserAddRoute
  '/user/add-batch': typeof AuthUserAddBatchRoute
  '/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/admin': typeof AuthAdminIndexRoute
  '/camera': typeof AuthCameraIndexRoute
  '/organization': typeof AuthOrganizationIndexRoute
  '/point': typeof AuthPointIndexRoute
  '/user': typeof AuthUserIndexRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/monitoring': typeof AuthMonitoringIndexLazyRoute
  '/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/admin/add': typeof AuthAdminAddRoute
  '/camera/add': typeof AuthCameraAddRoute
  '/organization/add': typeof AuthOrganizationAddRoute
  '/point/add': typeof AuthPointAddRoute
  '/user/add': typeof AuthUserAddRoute
  '/user/add-batch': typeof AuthUserAddBatchRoute
  '/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/admin': typeof AuthAdminIndexRoute
  '/camera': typeof AuthCameraIndexRoute
  '/organization': typeof AuthOrganizationIndexRoute
  '/point': typeof AuthPointIndexRoute
  '/user': typeof AuthUserIndexRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/monitoring': typeof AuthMonitoringIndexLazyRoute
  '/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/admin/add': typeof AuthAdminAddRoute
  '/_auth/camera/add': typeof AuthCameraAddRoute
  '/_auth/organization/add': typeof AuthOrganizationAddRoute
  '/_auth/point/add': typeof AuthPointAddRoute
  '/_auth/user/add': typeof AuthUserAddRoute
  '/_auth/user/add-batch': typeof AuthUserAddBatchRoute
  '/_auth/monitoring/history': typeof AuthMonitoringHistoryLazyRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/camera/': typeof AuthCameraIndexRoute
  '/_auth/organization/': typeof AuthOrganizationIndexRoute
  '/_auth/point/': typeof AuthPointIndexRoute
  '/_auth/user/': typeof AuthUserIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexLazyRoute
  '/_auth/monitoring/': typeof AuthMonitoringIndexLazyRoute
  '/_auth/admin/edit/$id': typeof AuthAdminEditIdLazyRoute
  '/_auth/camera/edit/$id': typeof AuthCameraEditIdLazyRoute
  '/_auth/organization/edit/$id': typeof AuthOrganizationEditIdLazyRoute
  '/_auth/point/edit/$id': typeof AuthPointEditIdLazyRoute
  '/_auth/user/edit/$id': typeof AuthUserEditIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/admin/add'
    | '/camera/add'
    | '/organization/add'
    | '/point/add'
    | '/user/add'
    | '/user/add-batch'
    | '/monitoring/history'
    | '/admin'
    | '/camera'
    | '/organization'
    | '/point'
    | '/user'
    | '/dashboard'
    | '/monitoring'
    | '/admin/edit/$id'
    | '/camera/edit/$id'
    | '/organization/edit/$id'
    | '/point/edit/$id'
    | '/user/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/admin/add'
    | '/camera/add'
    | '/organization/add'
    | '/point/add'
    | '/user/add'
    | '/user/add-batch'
    | '/monitoring/history'
    | '/admin'
    | '/camera'
    | '/organization'
    | '/point'
    | '/user'
    | '/dashboard'
    | '/monitoring'
    | '/admin/edit/$id'
    | '/camera/edit/$id'
    | '/organization/edit/$id'
    | '/point/edit/$id'
    | '/user/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_auth'
    | '/_auth/admin/add'
    | '/_auth/camera/add'
    | '/_auth/organization/add'
    | '/_auth/point/add'
    | '/_auth/user/add'
    | '/_auth/user/add-batch'
    | '/_auth/monitoring/history'
    | '/_auth/admin/'
    | '/_auth/camera/'
    | '/_auth/organization/'
    | '/_auth/point/'
    | '/_auth/user/'
    | '/_auth/dashboard/'
    | '/_auth/monitoring/'
    | '/_auth/admin/edit/$id'
    | '/_auth/camera/edit/$id'
    | '/_auth/organization/edit/$id'
    | '/_auth/point/edit/$id'
    | '/_auth/user/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/monitoring/': {
      id: '/_auth/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthMonitoringIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/': {
      id: '/_auth/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/': {
      id: '/_auth/point/'
      path: '/point'
      fullPath: '/point'
      preLoaderRoute: typeof AuthPointIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/': {
      id: '/_auth/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthOrganizationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/': {
      id: '/_auth/camera/'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof AuthCameraIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitoring/history': {
      id: '/_auth/monitoring/history'
      path: '/monitoring/history'
      fullPath: '/monitoring/history'
      preLoaderRoute: typeof AuthMonitoringHistoryLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/add-batch': {
      id: '/_auth/user/add-batch'
      path: '/user/add-batch'
      fullPath: '/user/add-batch'
      preLoaderRoute: typeof AuthUserAddBatchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/add': {
      id: '/_auth/user/add'
      path: '/user/add'
      fullPath: '/user/add'
      preLoaderRoute: typeof AuthUserAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/add': {
      id: '/_auth/point/add'
      path: '/point/add'
      fullPath: '/point/add'
      preLoaderRoute: typeof AuthPointAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/add': {
      id: '/_auth/organization/add'
      path: '/organization/add'
      fullPath: '/organization/add'
      preLoaderRoute: typeof AuthOrganizationAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/add': {
      id: '/_auth/camera/add'
      path: '/camera/add'
      fullPath: '/camera/add'
      preLoaderRoute: typeof AuthCameraAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/add': {
      id: '/_auth/admin/add'
      path: '/admin/add'
      fullPath: '/admin/add'
      preLoaderRoute: typeof AuthAdminAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/edit/$id': {
      id: '/_auth/user/edit/$id'
      path: '/user/edit/$id'
      fullPath: '/user/edit/$id'
      preLoaderRoute: typeof AuthUserEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/point/edit/$id': {
      id: '/_auth/point/edit/$id'
      path: '/point/edit/$id'
      fullPath: '/point/edit/$id'
      preLoaderRoute: typeof AuthPointEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organization/edit/$id': {
      id: '/_auth/organization/edit/$id'
      path: '/organization/edit/$id'
      fullPath: '/organization/edit/$id'
      preLoaderRoute: typeof AuthOrganizationEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/camera/edit/$id': {
      id: '/_auth/camera/edit/$id'
      path: '/camera/edit/$id'
      fullPath: '/camera/edit/$id'
      preLoaderRoute: typeof AuthCameraEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/edit/$id': {
      id: '/_auth/admin/edit/$id'
      path: '/admin/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthAdminEditIdLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminAddRoute: typeof AuthAdminAddRoute
  AuthCameraAddRoute: typeof AuthCameraAddRoute
  AuthOrganizationAddRoute: typeof AuthOrganizationAddRoute
  AuthPointAddRoute: typeof AuthPointAddRoute
  AuthUserAddRoute: typeof AuthUserAddRoute
  AuthUserAddBatchRoute: typeof AuthUserAddBatchRoute
  AuthMonitoringHistoryLazyRoute: typeof AuthMonitoringHistoryLazyRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthCameraIndexRoute: typeof AuthCameraIndexRoute
  AuthOrganizationIndexRoute: typeof AuthOrganizationIndexRoute
  AuthPointIndexRoute: typeof AuthPointIndexRoute
  AuthUserIndexRoute: typeof AuthUserIndexRoute
  AuthDashboardIndexLazyRoute: typeof AuthDashboardIndexLazyRoute
  AuthMonitoringIndexLazyRoute: typeof AuthMonitoringIndexLazyRoute
  AuthAdminEditIdLazyRoute: typeof AuthAdminEditIdLazyRoute
  AuthCameraEditIdLazyRoute: typeof AuthCameraEditIdLazyRoute
  AuthOrganizationEditIdLazyRoute: typeof AuthOrganizationEditIdLazyRoute
  AuthPointEditIdLazyRoute: typeof AuthPointEditIdLazyRoute
  AuthUserEditIdLazyRoute: typeof AuthUserEditIdLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminAddRoute: AuthAdminAddRoute,
  AuthCameraAddRoute: AuthCameraAddRoute,
  AuthOrganizationAddRoute: AuthOrganizationAddRoute,
  AuthPointAddRoute: AuthPointAddRoute,
  AuthUserAddRoute: AuthUserAddRoute,
  AuthUserAddBatchRoute: AuthUserAddBatchRoute,
  AuthMonitoringHistoryLazyRoute: AuthMonitoringHistoryLazyRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthCameraIndexRoute: AuthCameraIndexRoute,
  AuthOrganizationIndexRoute: AuthOrganizationIndexRoute,
  AuthPointIndexRoute: AuthPointIndexRoute,
  AuthUserIndexRoute: AuthUserIndexRoute,
  AuthDashboardIndexLazyRoute: AuthDashboardIndexLazyRoute,
  AuthMonitoringIndexLazyRoute: AuthMonitoringIndexLazyRoute,
  AuthAdminEditIdLazyRoute: AuthAdminEditIdLazyRoute,
  AuthCameraEditIdLazyRoute: AuthCameraEditIdLazyRoute,
  AuthOrganizationEditIdLazyRoute: AuthOrganizationEditIdLazyRoute,
  AuthPointEditIdLazyRoute: AuthPointEditIdLazyRoute,
  AuthUserEditIdLazyRoute: AuthUserEditIdLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
